canary_app/canary/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from canary.views import *


app_name = 'canary'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^start_stream/', start_stream, name='start_stream'),
    url(r'^stop_stream/', stop_stream, name='stop_stream'),
    url(r'^visualization/', visualization, name='visualization'),
    url(r'^results/', results, name='results'),
]

canary_app/canary_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('canary.urls'), name='canary')
]

canary_app/canary/models.py
from django.db import models

class UserKeyword(models.Model):
    keyword_name = models.CharField(max_length=50, null=True)


class Tweet(models.Model):
    """
        Contains pertinent data to tweets streamed from the Twitter API.
    """
    tweet_text = models.CharField(max_length=140, default='No Tweet Data. Weird.')
    sent_rating = models.DecimalField(max_digits=19, decimal_places=10)
    origin = models.CharField(max_length=140, null=True, default='No Location data. Weird.')
    search_keyword = models.ForeignKey(UserKeyword, null=True, on_delete=models.CASCADE)

canary_app/canary/views.py
from processor import *

from listener import Listener
from config import keys
from django.shortcuts import render
from django.http import HttpResponseRedirect

from tweepy import OAuthHandler, API, Stream

TweetProcessor = Processor()

auth = OAuthHandler(keys['consumer_key'], keys['consumer_secret'])
auth.set_access_token(keys['access_token'], keys['access_token_secret'])
api = API(auth)

listener = Listener(processor=TweetProcessor)
stream = Stream(auth=api.auth, listener=listener)


def index(request):
    """
    Render landing template.
    :param request:
    :return:
    """
    template_name = 'canary/index.html'
    return render(request, template_name, {})


def start_stream(request):
    """
    Initiate connection to Twitter Streaming API.
    :param request:
    :return:
    """
    query = str(request.POST['search'])

    TweetProcessor.clear()
    TweetProcessor.set_keyword(query)
    stream.filter(track=[query], is_async=True)

    return HttpResponseRedirect('/visualization')


def stop_stream(request):
    """
    Close connection with Twitter stream.
    :param request:
    :return:
    """
    stream.disconnect()
    return HttpResponseRedirect('/results')


def visualization(request):
    """
    Render visualization template, including data stream
    :param request:
    :return:
    """

    template_name = 'canary/visualization.html'
    data = TweetProcessor.get_data()
    return render(request, template_name, data)


def results(request):
    """
    Render results template
    :param request:
    :return:
    """

    template_name = 'canary/results.html'
    data = TweetProcessor.get_data()
    return render(request, template_name, data)

canary_app/canary/templates/canary/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>canary</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:100i,300,300i,400,400i,500,700" rel="stylesheet">
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>
    <body>
        <div class='container'>
            {% block content %}
            <div id='search-wrap'>
                <div class='row'>
                    <div class='center-align'>
                        <h1 class="header header-italic no-select">canary</h1>
                    </div>
                </div>
                <form action="{% url 'canary:start_stream' %}" method="post">
                    {% csrf_token %}
                    <div class='row'>
                        <div class='center-align'>
                            <input id='landing-search-field' type="text" name="search" placeholder="What do you want to search for?">
                        </div>
                    </div>
                    <div class='row'>
                        <div id='start-stream' class='center-align'>
                            <button id="start" class='btn waves-effect waves-light grey-text text-darken-2 grey lighten-2' type="submit">Go</button>
                        </div>
                    </div>
                </form>
                <div class='row'>
                    <div class='center-align'>
                        <img id='twitter-logo' src="{% static 'img/Twitter_Logo_Blue.png' %}">
                        <span class='powered'>Powered by the Twitter Streaming API</span>
                    </div>
                </div>
            </div>
            {% endblock %}
        </div>
        <script type="text/javascript">
            let SentimentValues = {'positive': 0, 'negative': 0, 'neutral': 0}
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

canary_app/canary/templates/canary/landing.html
{% extends 'canary/index.html' %}

{% load static %}
<div id='data-wrapper' class='z-depth-2'>
{% block content %}
      <h1>.....</h1>
{% endblock %}
</div>

canary_app/canary/templates/canary/results.html
{% extends 'canary/index.html' %}

{% block content %}
{% load static %}

<!-- CONTROLS -->
<div class="controls">
  <form action="{% url 'canary:start_stream' %}" method="post">
      {% csrf_token %}
      <div class='row'>
          <div class='center-align'>
            <input id='landing-search-field' type="text" name="search" placeholder="New Search">
          </div>
      </div>
      <div class='row'>
          <div id='start-stream' class='center-align'>
            <button id="start" class='btn waves-effect waves-light grey-text text-darken-2 grey lighten-3' type="submit">Go</button>
          </div>
      </div>
  </form>
</div>

<div id='vis-wrap'>
  <div id='data-wrapper'>

    <div id='visualization' action="{% url 'canary:visualization' %}" method='get'>
      <div class='row'>
        <div id='search-keyword' class='left-align'>
          <h1 class="header header-regular no-select">Results for <i>'{{positive.keyword}}'</i></h1>
        </div>
      </div>

      <div class='row'>
        <div id='donut' class='col s6 left-align'>
            <script type="text/javascript">
              google.charts.load("current", {packages:["corechart"]});
              google.charts.setOnLoadCallback(drawChart);
              function drawChart() {
                var data = google.visualization.arrayToDataTable([
                  ['Sentiment', 'Count'],
                  ['Positive',     {{positive.sentiment_value}}],
                  ['Neutral',  {{neutral.sentiment_value}}],
                  ['Negative',      {{negative.sentiment_value}}]
                ]);

                var options = {
                  title: 'Tweet Sentiment',
                  'fontWeight': '200',
                  backgroundColor: 'transparent',
                  is3D: 'true',
                  fontSize: '16',
                  fontName: 'Helvetica',
                  fontWeight: '200',
                  chartArea: {'width': '80%', 'height': '80%'},
                  legend: {'position': 'bottom'},
                  circle: {'width': '500px'},
                  colors: ['#5DCF72', '#D0D16E', '#D17571']
                  /////// positive //// neutral // negative
                };

                var chart = new google.visualization.PieChart(document.getElementById('piechart'));
                chart.draw(data, options);
              }

            </script>

            <div id="piechart" style="width: 400px; height: 400px;"></div>
        </div>

        <div id='positive' class='col s4 origin-wrapper'>
            <div class='left-align tweet-overview'>
              <span class='tweet-data'><b>{{positive.sentiment_value}}</b> positive tweets</span>
            </div>
            <div class='right-align tweet-origin'>
              <span class='tweet-data'>Origins</span>
            </div>
          <div id='positive-locations' class='right-align'>
            {% for loc in positive.origins %}
                {% if loc != "Unknown Origin" %}
                    <h6 class='tweet-data location'>{{loc}}</h6>
                {% endif %}
            {% endfor %}
          </div>
        </div>

        <div id='neutral' class='col s4 origin-wrapper'>
          <div class='left-align tweet-overview'>
            <span class='tweet-data'><b>{{neutral.sentiment_value}}</b> neutral tweets</span>
          </div>
          <div class='right-align tweet-origin'>
            <span class='tweet-data'>Origins</span>
          </div>
          <div id='neutral-locations' class='right-align'>
            {% for loc in neutral.origins %}
                {% if loc != "Unknown Origin" %}
                    <h6 class='tweet-data location'>{{loc}}</h6>
                {% endif %}
            {% endfor %}
          </div>
        </div>

        <div id='negative' class='col s4 origin-wrapper'>
          <div class='left-align tweet-overview'>
            <span class='tweet-data'><b>{{negative.sentiment_value}}</b> negative tweets</span>
          </div>
          <div class='right-align tweet-origin'>
            <span class='tweet-data'>Origins</span>
          </div>
          <div id='negative-locations' class='tweet-data right-align'>
            {% for loc in negative.origins %}
                {% if loc != "Unknown Origin" %}
                    <h6 class='tweet-data location'>{{loc}}</h6>
                {% endif %}
            {% endfor %}
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

canary_app/canary/templates/canary/visualization.html
{% extends 'canary/index.html' %}

{% load static %}
{% block content %}
<!-- CONTROLS -->
<div class="controls">
  <form action="{% url 'canary:stop_stream' %}">
      {% csrf_token %}
      <div class='row'>
        <div class='stop-stream center-align'>
            <button id="stop" class='btn waves-effect waves-light btn-large grey-text text-darken-2 #b3e5fc grey lighten-2' type="submit">Stop Stream</button>
        </div>
      </div>
  </form>
</div>

<div id='vis-wrap'>
  <div id='data-wrapper'>
    <div id='visualization' action="{% url 'canary:visualization' %}" method='get'>

      <div class='row'>
        <div id='search-keyword'>
          <h1 class="header header-regular no-select">Streaming results for <i>'{{positive.keyword}}'</i></h1>
        </div>
        <div class='loader center-align'>
            <div class="preloader-wrapper big active">
                <div class="spinner-layer spinner-yellow-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                        </div><div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
      </div>

      <div class='row viz-elements'>
        <div id='donut' class='col s6 left-align'>
            <script type="text/javascript">
                SentimentValues.positive = {{ positive.sentiment_value }};
                SentimentValues.negative = {{ negative.sentiment_value }};
                SentimentValues.neutral = {{ neutral.sentiment_value }};

                google.charts.load("current", {packages:["corechart"]});
                google.charts.setOnLoadCallback(drawChart);
                function drawChart() {
                    let data = google.visualization.arrayToDataTable([
                        ['Sentiment', 'Count'],
                        ['Positive', SentimentValues.positive],
                        ['Neutral', SentimentValues.neutral],
                        ['Negative', SentimentValues.negative]
                    ]);

                    let options = {
                      title: 'Tweet Sentiment',
                      sliceVisibilityThreshold: 0,
                      backgroundColor: 'transparent',
                      is3D: 'true',
                      fontSize: '16',
                      fontName: 'Helvetica',
                      fontWeight: '200',
                      chartArea: {'width': '80%', 'height': '80%'},
                      legend: {'position': 'bottom'},
                      circle: {'width': '500px'},
                      colors: ['#5DCF72', '#D0D16E', '#D17571']
                    };

                    let chart = new google.visualization.PieChart(document.getElementById('piechart'));
                    chart.draw(data, options);
                }

            </script>

          <div id="piechart" style="width: 400px; height: 400px;"></div>
        </div>

        <!-- POSITIVE SENTIMENT CARD -->
        <div id='positive' class='col s4 origin-wrapper'>
            <div class='left-align tweet-overview'>
              <span class='tweet-data'><b><span class='sentiment-count'>{{positive.sentiment_value}}</span></b> positive tweet origins</span>
            </div>
            <div id='positive-locations' class='right-align'>
            {% for loc in positive.origins %}
                {% if loc != "Unknown Origin" %}
                    <h6 class='tweet-data location'>{{loc}}</h6>
                {% endif %}
            {% endfor %}
          </div>
        </div>

        <!-- NEUTRAL SENTIMENT CARD -->
        <div id='neutral' class='col s4 origin-wrapper'>
          <div class='left-align tweet-overview'>
            <span class='tweet-data'><b><span class='sentiment-count'>{{neutral.sentiment_value}}</span></b> neutral tweet origins</span>
          </div>
          <div id='neutral-locations' class='right-align'>
            {% for loc in neutral.origins %}
            {% if loc != "Unknown Origin" %}
            <h6 class='tweet-data location'>{{loc}}</h6>
            {% endif %}
            {% endfor %}
          </div>
        </div>

        <!-- NEGATIVE SENTIMENT CARD -->
        <div id='negative' class='col s4 origin-wrapper'>
          <div class='left-align tweet-overview'>
            <span class='tweet-data'><b><span class='sentiment-count'>{{negative.sentiment_value}}</span></b> negative tweet origins</span>
          </div>
          <div id='negative-locations' class='tweet-data right-align'>
            {% for loc in negative.origins %}
            {% if loc != "Unknown Origin" %}
            <h6 class='tweet-data location'>{{loc}}</h6>
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/refresh.js' %}"></script>
{% endblock %}